### ISSUE TITLE
Incompatability with older OpenGL Versions

### ISSUE THREAD

**Issue by Sunrobbie** [SinTh0r4s/HydroEnergy#23]
From the discord, it's been brought up that the rendering of the dams will crash your game if your Opengl version is lower than 4, specifically the glGenVertexArrays function.
Attached are the relevant crash reports from Alastor.

[crash-2021-04-30_17.03.59-client.txt](https://github.com/SinTh0r4s/HydroEnergy/files/6618191/crash-2021-04-30_17.03.59-client.txt)
[crash-2021-04-30_17.17.47-server.txt](https://github.com/SinTh0r4s/HydroEnergy/files/6618208/crash-2021-04-30_17.17.47-server.txt)

**Comment by SinTh0r4s** [comment]
Thanks for letting me know!

glGenVertexArrays is OpenGL 3.0 and a very, very old standard. Sadly, there is not too much i can to do about it. I need that call. My laptop is old and barely runs GTNH, but already has the newest OpenGL version. I don't expect many people to have a problem with it.

**Comment by Alastors** [comment]
Just putting this for reference even though I have mentioned it to you, I figure it should be here too. MacOS doesn't have support for opengl past 2.1 or so since 10.14 mojave, switching main support to Apple's in-house graphics API. So this is more than likely the issue ;-;. 

And as I mentioned I'd put it here just for future's reference:

Is there is a way to not show the dam water graphically to those who wouldn't be able to see it (that being those on mac in this case) and still use it despite that fact? That would at least solve the issue of people potentially crashing when rendering it? Like how you got the mod to show the opengl version, maybe making that a gate to render the dam water?


I know you're working on it, this is more for other's reference than anything else.

**Comment by SinTh0r4s** [comment]
I implemented fallback rendering for the time being. Won't be perfect, but it won't crash for now
